"""Sports-science PDF snippets for the Qdrant certification hands-on.

A flat list of payload-ready dicts — one short (~9-10 line) excerpt per paper in
``assets/`` — mirroring the ``documents = [ {...}, ... ]`` shape used in
``11_semantic_movie_search.py``. Load directly and attach as Qdrant payloads::

    from sports_science_documents import documents
    from qdrant_client import models

    points = [
        models.PointStruct(id=i, vector=encoder.encode(d["text"]).tolist(), payload=d)
        for i, d in enumerate(documents)
    ]

Auto-generated by scratchpad/extract_snippets.py — do not edit by hand.
"""

documents: list[dict] = [{'name': '10.1007@s40279-012-0002-0',
  'title': 'Mathieu Ne´de´lec • Alan McCall • Chris Carling •',
  'text': 'Part II—Recovery Strategies Mathieu Ne´de´lec • Alan McCall • Chris Carling • Franck '
          'Legall • Serge Berthoin • Gregory Dupont Published online: 16 November 2012 Springer '
          'International Publishing Switzerland 2012 In the formerly published part I of this '
          'two-part review, we examined fatigue after soccer matchplay and recovery kinetics of '
          'physical performance, and cognitive, subjective and biological markers. To reduce the '
          'magni- tude of fatigue and to accelerate the time to fully recover',
  'year': 2012,
  'source_file': '10.1007@s40279-012-0002-0.pdf',
  'n_words': 73},
 {'name': '40279_2018_Article_935',
  'title': 'Monitoring of Post-match Fatigue in Professional Soccer:',
  'text': 'Monitoring of Post-match Fatigue in Professional Soccer: Welcome to the Real World • '
          'Mathieu Lacome2 • Alan McCall3,4 • Gregory Dupont5 • Franck Le Gall5 • Ben Simpson2 • '
          'Martin Buchheit2 Published online: 8 May 2018 Abstract Participation in soccer '
          'match-play leads to acute physical disturbances in players over subsequent hours and '
          'days. Inadequate time for rest and regeneration between matches can expose players to '
          'the risk of training and competing whilst not entirely recovered. In professional',
  'year': 2018,
  'source_file': '40279_2018_Article_935.pdf',
  'n_words': 77},
 {'name': '40279_2023_Article_1944',
  'title': 'Sports Medicine (2024) 54:623–643',
  'text': 'Sports Medicine (2024) 54:623–643 https://doi.org/10.1007/s40279-023-01944-8 The '
          'Effects of Strength, Plyometric and Combined Training on Strength, Power and Speed '
          'Characteristics in High‑Level, Highly Trained Male Youth Soccer Players: A Systematic '
          'Review Jon L. Oliver1,2 · Akhilesh Kumar Ramachandran1 · Utkarsh Singh3 · Rodrigo '
          'Ramirez‑Campillo4 · Rhodri S. Lloyd1,2 Accepted: 25 September 2023 / Published online: '
          '28 October 2023 Background Male youth soccer players competing at a high level will '
          'typically engage in large volumes of soccer training from a young age. However, it is '
          'not known whether the high levels of habitual training that these high-performing '
          'players are exposed to limit their ability to respond to strength, plyometric or '
          'combined training interventions.',
  'year': 2023,
  'source_file': '40279_2023_Article_1944.pdf',
  'n_words': 111},
 {'name': 'Bowen2020PhD',
  'title': 'WORKLOADS AND INJURY RISK IN PREMIER',
  'text': 'WORKLOADS AND INJURY RISK IN PREMIER A thesis submitted to the University of Birmingham '
          'School of Sport, Exercise and Rehabilitation Sciences College of Life and Environmental '
          'Sciences University of Birmingham Research Archive This unpublished thesis/dissertation '
          'is copyright of the author and/or third parties. The intellectual property rights of '
          'the author or third parties in respect of this work are as defined by The Copyright '
          'Designs and Patents Act 1988 or as modified by any successor legislation. Any use made '
          'of information contained in this thesis/dissertation must be in',
  'year': 2020,
  'source_file': 'Bowen2020PhD.pdf',
  'n_words': 88},
 {'name': 'Effects of strength training on squat and sprint performance in soccer players '
          '_Accepted -USIR_',
  'title': 'Effects of strength training on squat and sprint performance in soccer players',
  'text': 'Effects of strength training on squat and sprint performance in soccer players William '
          'J. Styles1,2, Martyn J. Matthews2 & Paul Comfort2# 1Glasgow Celtic Football Club, '
          'Medical Department, 95 Kerrydale Street, Glasgow. 2Human Performance Laboratory, '
          'Directorate of Sport, Exercise, and Physiotherapy, University of Salford, Greater '
          'Manchester, M6 6PU. United Kingdom #Corresponding Author: Paul Comfort – '
          'p.comfort@salford.ac.uk Preferred running head: Strength training in soccer players '
          'Effects of strength training on squat and sprint performance in soccer players',
  'year': None,
  'source_file': 'Effects of strength training on squat and sprint performance in soccer players '
                 '_Accepted -USIR_.pdf',
  'n_words': 75},
 {'name': 'Gabbett_2016_Training-injuryparadox_Trainsmarterandharder_BJSM',
  'title': 'The training—injury prevention paradox: should',
  'text': 'The training—injury prevention paradox: should athletes be training smarter and harder? '
          '1School of Exercise Science, Australian Catholic University, 2School of Human Movement '
          'Dr Tim J Gabbett, School of Exercise Science, Australian Catholic University, 1100 '
          'Accepted 16 November 2015 To cite: Gabbett TJ. Br J',
  'year': 2016,
  'source_file': 'Gabbett_2016_Training-injuryparadox_Trainsmarterandharder_BJSM.pdf',
  'n_words': 44},
 {'name': 'JBS-39-102924',
  'title': 'Biology of Sport, Vol. 39 No1, 2022 115',
  'text': 'Biology of Sport, Vol. 39 No1, 2022 115 Weekly external load in soccer Football '
          '(soccer) is a complex sport where a multitude of tactical, technical and physical '
          'elements modulate performance [1]. Con\xad temporary approaches examining the '
          'integrative nature of the game, in which an array of factors are synthesised, provide '
          'greater insights into a player’s positional and match requirements [2–3]. These '
          'multifaceted demands accumulate across the season, particularly when matches are played '
          'with minimal recovery [4]. Accordingly, practitioners modify training and competition '
          'demands during the',
  'year': 2022,
  'source_file': 'JBS-39-102924.pdf',
  'n_words': 85},
 {'name': 'JBS-39-106148',
  'title': 'Biology of Sport, Vol. 39 No2, 2022 397',
  'text': 'Biology of Sport, Vol. 39 No2, 2022 397 Workload Profile in Professional Soccer '
          'Electronic performance tracking systems provide valuable information for strength and '
          'conditioning coaches, sports scientists, and research\xad ers since a better '
          'understanding of the volume and intensity of each training session and match is '
          'possible [1, 2]. Specifically, these data allow the analysis of the workload, and '
          'therefore, programming strat\xad egies for the periodized training plan may be adopted '
          '[3]. In addition, these are objective data (e.g., distance covered, high-speed running '
          'distance, total number of accelerations) that provide further informa\xad',
  'year': 2022,
  'source_file': 'JBS-39-106148.pdf',
  'n_words': 92},
 {'name': 'akenhead2016',
  'title': 'International Journal of Sports Physiology and Performance, 2016, 11, 587 -593',
  'text': 'International Journal of Sports Physiology and Performance, 2016, 11, 587 -593 '
          'http://dx.doi.org/10.1123/ijspp.2015-0331 © 2016 Human Kinetics, Inc. The authors are '
          'with the National Sports Medicine Program, Excellence in Football Project, Aspetar '
          'Qatar Orthopedic and Sports Medicine Hos- pital, Doha, Qatar. Address author '
          'correspondence to Richard Akenhead at richard.akenhead@aspetar.com. National Sports '
          'Medicine Program, Excellence in Football Project, As- petar Qatar Orthopedic and Sports '
          'Medicine Hospital, Doha, Qatar Training Load and Player Monitoring in High-Level '
          'Football:',
  'year': 2016,
  'source_file': 'akenhead2016.pdf',
  'n_words': 74},
 {'name': 'anderson2015',
  'title': 'Full Terms & Conditions of access and use can be found at',
  'text': 'Full Terms & Conditions of access and use can be found at '
          'http://www.tandfonline.com/action/journalInformation?journalCode=rjsp20 Download by: '
          '[University of Nebraska, Lincoln] Date: 05 November 2015, At: 06:40 Journal of Sports '
          'Sciences ISSN: 0264-0414 (Print) 1466-447X (Online) Journal homepage: '
          'http://www.tandfonline.com/loi/rjsp20 Quantification of training load during one-, two- '
          'and three-game week schedules in professional soccer players from the English Premier '
          'League: implications for carbohydrate periodisation',
  'year': 2015,
  'source_file': 'anderson2015.pdf',
  'n_words': 61},
 {'name': 'bjsports-2015-095788',
  'title': 'The training—injury prevention paradox: should',
  'text': 'The training—injury prevention paradox: should athletes be training smarter and harder? '
          '1School of Exercise Science, Australian Catholic University, 2School of Human Movement '
          'Dr Tim J Gabbett, School of Exercise Science, Australian Catholic University, 1100 '
          'Accepted 16 November 2015 To cite: Gabbett TJ. Br J',
  'year': 2015,
  'source_file': 'bjsports-2015-095788.pdf',
  'n_words': 44},
 {'name': 'bjsports-2015-095820',
  'title': 'Accumulated workloads and the acute:chronic',
  'text': 'Accumulated workloads and the acute:chronic workload ratio relate to injury risk in '
          'elite youth Laura Bowen,1,2 Aleksander Stefan Gross,2 Mo Gimpel,2 François-Xavier Li1 '
          'Aim The purpose of this study was to investigate the relationship between physical '
          'workload and injury risk in elite youth football players. Methods The workload data and '
          'injury incidence of 32 players were monitored throughout 2 seasons. Multiple regression '
          'was used to compare cumulative (1, 2, 3 and 4-weekly) loads and acute:chronic (A:C)',
  'year': 2015,
  'source_file': 'bjsports-2015-095820.pdf',
  'n_words': 76},
 {'name': 'bourdon2017',
  'title': 'International Journal of Sports Physiology and Performance, 2017, 12, S2-161 -S2-170',
  'text': 'International Journal of Sports Physiology and Performance, 2017, 12, S2-161 -S2-170 © '
          '2017 Human Kinetics, Inc. Primary affiliations: Bourdon, Cardinale, Murray, and Cable, '
          'Sport Sci- ence, and Varley and Gregson, Football Performance and Science, Aspire '
          'Academy, Doha, Qatar. Gastin, School of Exercise and Nutrition Sciences, Deakin '
          'University, Melbourne, Australia. Kellmann, Faculty of Sport Science, Ruhr-University '
          'Bochum, Germany. Gabbett, Inst for Resilient Regions, University of Southern '
          'Queensland, Ipswich, Australia. Coutts, Sport and Exercise Discipline Group, University '
          'of Technology Sydney, Australia. Burgess, Port Adelaide Football Club, Adelaide, '
          'Australia.',
  'year': 2017,
  'source_file': 'bourdon2017.pdf',
  'n_words': 86},
 {'name': 'disalvo2007',
  'title': 'Over the last two decades, there has been a growing interest in',
  'text': 'Over the last two decades, there has been a growing interest in match-analyses of '
          'soccer [1,4,6,11,12,15–17,22,24,25,29,32, 34]. The practical value of such analyses is '
          'that well chosen per- formance indicators can help coaches to identify good and bad '
          'performances of individuals or teams. In this respect, match-an- alysis has been '
          'helpful in identifying the physiological demands of the sport, and in examining how a '
          'particular player compares to the needs of his event. Understanding the physiological '
          'load imposed on top-level soccer players according to their positional role during '
          'competitive matches (activity profile, distance cov-',
  'year': 2007,
  'source_file': 'disalvo2007.pdf',
  'n_words': 94},
 {'name': 'disalvo2009',
  'title': 'Di Salvo V et al. Analysis of High Intensity Activity … Int J Sports Med 2009; 30: 205 '
           '– 212',
  'text': 'Di Salvo V et al. Analysis of High Intensity Activity … Int J Sports Med 2009; 30: 205 '
          '– 212 DOI 10.1055/s-0028-1105950 Int J Sports Med 2009; 30: 205 – 212 © Georg Thieme '
          'Verlag KG Stuttgart · New York Research Institute for Sport Tel.: + 44 (0) / 151 / 23 '
          '143 30 Fax: + 44 (0) / 151 / 23 143 53 Analysis of High Intensity Activity in Premier '
          'stresses the aerobic energy system [1] . Anaerobic',
  'year': 2009,
  'source_file': 'disalvo2009.pdf',
  'n_words': 79},
 {'name': 'fnins-11-00612',
  'title': 'Frontiers in Neuroscience | www.frontiersin.org',
  'text': 'published: 02 November 2017 doi: 10.3389/fnins.2017.00612 Frontiers in Neuroscience | '
          'www.frontiersin.org November 2017 | Volume 11 | Article 612 Università degli Studi “G. '
          'd’Annunzio” Midwestern University, United States Masaryk University, Czechia This '
          'article was submitted to Frontiers in Neuroscience Received: 16 December 2016',
  'year': 2017,
  'source_file': 'fnins-11-00612.pdf',
  'n_words': 43},
 {'name': 'fphys-11-00944',
  'title': 'Frontiers in Physiology | www.frontiersin.org',
  'text': 'published: 20 August 2020 doi: 10.3389/fphys.2020.00944 Frontiers in Physiology | '
          'www.frontiersin.org August 2020 | Volume 11 | Article 944 University of Verona, Italy '
          'Pantelis Theodoros Nikolaidis, University of West Attica, Greece University Hospital '
          'Zurich, Switzerland urs.granacher@uni-potsdam.de hassane.zouhal@univ-rennes2.fr',
  'year': 2020,
  'source_file': 'fphys-11-00944.pdf',
  'n_words': 37},
 {'name': 'ijerph-19-09385',
  'title': 'Citation: Selmi, O.; Ouergui, I.;',
  'text': 'Citation: Selmi, O.; Ouergui, I.; Muscella, A.; My, G.; Marsigliante, S.; Nobari, H.; '
          'Suzuki, K.; Bouassida, A. Monitoring Psychometric States of Recovery to Improve '
          'Performance in Soccer Players: A Brief Review. Int. J. Environ. Res. Public Health '
          '2022, 19, 9385. https://doi.org/10.3390/ Academic Editor: Paul B. Tchounwou Publisher’s '
          'Note: MDPI stays neutral',
  'year': 2022,
  'source_file': 'ijerph-19-09385.pdf',
  'n_words': 51},
 {'name': 'impellizzeri2004',
  'title': 'Use of RPE-Based Training Load in Soccer',
  'text': "Use of RPE-Based Training Load in Soccer FRANCO M. IMPELLIZZERI', ERMANNO RAMPININI', "
          "AARON J. COUTTS2, ALDO SASSI', and SAMUELE M. MARCORA3 'Hiuman Peiformance Lab, S.S. "
          'MAPEI, Castellanza, Varese, ITALY; 2School of Leisutre, Sport and Tourism, University '
          'of Technology, Sydney, AUSTRALIA; and 3School of Sport, Health, and Exercise Sciences, '
          'University of Wales-Balngor, IMPELLIZZERI, F. M._ E. RAMPININI, A. J. COUTTS, A. SASSI, '
          'and S. M. MARCORA. Use of RPE-Based Training Load in Soccer. Med. Sce. Sports Exerc., '
          'Vol. 36, No. 6, pp. 1042-1047, 2004. Purpose: The ability to accurately control and '
          'monitor internal training load is an important aspect of effective coaching. The aim of '
          'this study was to apply in soccer the RPE-based method proposed by Foster et al. to '
          'quantify internal training load (session-RPE) and to assess its correlatiois with '
          'various methods used to determine internal training load based on the HR response to '
          'exercise. Methods: Nineteeii young soccer players (mean + SD: age 17.6 ± 0.7',
  'year': 2004,
  'source_file': 'impellizzeri2004.pdf',
  'n_words': 158},
 {'name': 'impellizzeri2019',
  'title': 'Internal and External Training Load: 15 Years On',
  'text': 'Internal and External Training Load: 15 Years On Franco M. Impellizzeri, Samuele M. '
          'Marcora, and Aaron J. Coutts Exercise is a stressor that induces various '
          'psychophysiological responses, which mediate cellular adaptations in many organ '
          'systems. To maximize this adaptive response, coaches and scientists need to control the '
          'stress applied to the athlete at the individual level. To achieve this, precise control '
          'and manipulation of the training load are required. In 2003, the authors introduced a '
          'theoretical framework to deﬁne and conceptualize the measurable constructs of the '
          'training process. They described training load as having 2 measurable components: '
          'internal and external load. The aim of this commentary is to extend, clarify, and reﬁne '
          'both the theoretical framework and the deﬁnitions of internal and external training '
          'load to avoid misinterpretation of Keywords: workload, exercise training, stimulus, '
          'stressor, psychobiological response The concepts of internal and external training load '
          'were ﬁrst',
  'year': 2019,
  'source_file': 'impellizzeri2019.pdf',
  'n_words': 147},
 {'name': 'jaspers2018',
  'title': 'is scarce. This study examined',
  'text': 'www.elsevier.com/locate/jsams is scarce. This study examined >20 km h−1), number of '
          'accelerations (ACCeff; >1 m s−2), number 1-, 2-, 3-, 4-weekly loads ratios (ACWR) were '
          'calculated and split into low, medium to focus on their speciﬁc Results: In total, 64 '
          'overuse injuries by TD, DECeff, and RPE multiplied by duration.',
  'year': 2018,
  'source_file': 'jaspers2018.pdf',
  'n_words': 50},
 {'name': 'malone2015',
  'title': '“Seasonal Training Load Quantification in Elite English Premier League Soccer Players” '
           'by Malone JJ et al.',
  'text': '“Seasonal Training Load Quantification in Elite English Premier League Soccer Players” '
          'by Malone JJ et al. International Journal of Sports Physiology and Performance © 2014 '
          'Human Kinetics, Inc. Note. This article will be published in a forthcoming issue of the '
          'International Journal of Sports Physiology and Performance. The article appears here in '
          'its accepted, peer-reviewed form, as it was provided by the submitting author. It has '
          'not been copyedited, proofread, or formatted by the publisher. Section: Original '
          'Investigation Article Title: Seasonal Training Load Quantification in Elite English '
          'Premier League Soccer',
  'year': 2015,
  'source_file': 'malone2015.pdf',
  'n_words': 90},
 {'name': 'malone2017',
  'title': 'and injury risk in elite profes-',
  'text': 'www.elsevier.com/locate/jsams and injury risk in elite profes- ± SD age of 25.3 ± 3.1 '
          'yr) from within a one season study. a test of intermittent-aerobic AU were at '
          'signiﬁcantly group of ≤1500 AU (OR = 1.95, p = 0.006). were better able to tolerate '
          'training load than players with lower ﬁtness levels (OR = 4.52, p = 0.011).',
  'year': 2017,
  'source_file': 'malone2017.pdf',
  'n_words': 58},
 {'name': 'malone2018',
  'title': 'of injury risk were also investigated.',
  'text': 'www.elsevier.com/locate/jsams This study investigated of the 30–15 intermittent test '
          '(30–15 VIFT) and high of injury risk were also investigated. 37 elite soccer players '
          'from one elite the HSR (>14.4 km h−1) and SR (>19.8 Lower limb injuries were also '
          'recorded. load and GPS data were modelled Injury risk was higher for players',
  'year': 2018,
  'source_file': 'malone2018.pdf',
  'n_words': 52},
 {'name': 's40279-024-02088-z',
  'title': 'Sports Medicine (2024) 54:2841–2864',
  'text': 'Sports Medicine (2024) 54:2841–2864 https://doi.org/10.1007/s40279-024-02088-z The '
          'Influence of Playing Position on Physical, Physiological, and Technical Demands in '
          'Adult Male Soccer Matches: A Systematic Scoping Review with Evidence Gap Map Hugo '
          'Sarmento1 · Diogo V. Martinho1,2 · Élvio R. Gouveia2,3,4 · José Afonso5 · Paweł Chmura6 '
          '· Adam Field7 · Nestor Ordoñez Savedra8 · Rafael Oliveira9,10 · Gibson Praça11 · Rui '
          'Silva12,13 · Joel Barrera‑Díaz1 · Filipe Manuel Clemente12,13,14 Accepted: 27 July 2024 '
          '/ Published online: 11 September 2024 Background There has been an increase in studies '
          'examining the demands of soccer relative to each playing position in recent',
  'year': 2024,
  'source_file': 's40279-024-02088-z.pdf',
  'n_words': 98},
 {'name': 's40798-015-0006-z',
  'title': 'Strength training in soccer with a specific focus',
  'text': 'Strength training in soccer with a specific focus on highly trained players João R '
          'Silva1,2*, George P Nassis1 and Antonio Rebelo2 Background: Data concerning the '
          'physical demands of soccer (e.g., activity pattern) suggest that a high level of '
          'performance requires well-developed neuromuscular function (NF). Proficient NF may be '
          'relevant to maintain and/ or increase players’ short- (intense periods of '
          'soccer-specific activity; accelerations, decelerations, and sprinting) and long-term '
          'performance during a match and throughout the season. Objective: This review examines '
          'the extent to which distinct modes of strength training improve soccer players’ '
          'performance, as well as the effects of concurrent strength and endurance training on '
          'the physical capacity Data sources: A selection of studies was performed in two '
          'screening phases. The first phase consisted of',
  'year': None,
  'source_file': 's40798-015-0006-z.pdf',
  'n_words': 124},
 {'name': 'v038p00285',
  'title': 'Strong correlation of maximal squat strength with sprint',
  'text': 'Strong correlation of maximal squat strength with sprint performance and vertical jump '
          'height in elite soccer players U Wisløff, C Castagna, J Helgerud, R Jones, J Hoff . . . '
          '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . '
          '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . '
          '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . '
          '. . . . . . . . . . . . . . . Dr Wisløff, Department of University of Science and . . . '
          '. . . . . . . . . . . . . . . . . . . . Br J Sports Med 2004;38:285–288. doi: '
          '10.1136/bjsm.2002.002071 Background: A high level of strength is inherent in elite '
          'soccer play, but the relation between maximal',
  'year': 2003,
  'source_file': 'v038p00285.pdf',
  'n_words': 232}]
